export const VERSIONS_TEMPLATE = `terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    {{#if hasDatabase}}
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
    {{/if}}
  }
}

provider "aws" {
  region = var.aws_region
}
`;

export const VARIABLES_TEMPLATE = `{{#each variables}}
variable "{{name}}" {
  type        = {{{type}}}
  {{#if hasDefault}}
  default     = {{{defaultValue}}}
  {{/if}}
  description = "{{description}}"
}

{{/each}}
`;

export const OUTPUTS_TEMPLATE = `{{#each outputs}}
output "{{name}}" {
  value       = {{{value}}}
  description = "{{description}}"
}

{{/each}}
`;

export const MAIN_TEMPLATE = `# Generated by AI Terraform Architect (Ata)
# Project: {{projectName}}
# Version: {{versionNumber}}
# Generation ID: {{generationId}}

{{#if hasDatabase}}
# Generate a secure password for the RDS database
resource "random_password" "db_pass" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}
{{/if}}

{{#each modules}}
module "{{moduleName}}" {
  source = "./modules/{{{sourcePath}}}"

  {{#each variables}}
  {{key}} = {{{value}}}
  {{/each}}
}

{{/each}}
`;

export const TFVARS_TEMPLATE = `{{#each tfvars}}
{{key}} = {{{value}}}
{{/each}}
`;
